### ISSUE TITLE
One spelling mistake

### ISSUE THREAD

**Issue by guizi597** [ngl567/GANA-FewShotKGC#17]
https://github.com/ngl567/GANA-FewShotKGC/blob/96dc8b3d81b685cb4ecdb8ea4e495fbc066e3ba9/main_gana.py#L1
![image](https://user-images.githubusercontent.com/80182711/220272957-0b054c9d-1b46-444a-8966-b075bc16067d.png)
Hi, I think "from trainer_gann import *" should be "from trainer_gana import *", it's just a small spelling mistake.

**Comment by ngl567** [comment]
Thank you for your comment. The mistake has been handled.
